name: Docker Build ECR and Push
description: Docker build and ECR push
inputs:
    aws-access-key-id:
        required: true
    aws-secret-access-key:
        required: true
    aws-region:
        required: false
        default: ap-northeast-2
    repository:
        required: true
    image-tag:
        required: false
        default: latest
    build-args:
        required: false
        default: ""
    build-contexts:
        required: false
        default: ""
    cache-from:
        required: false
        default: type=gha
    cache-to:
        required: false
        default: type=gha,mode=max
    context:
        required: false
        default: .
    file:
        required: false
        default: ./Dockerfile
    push:
        required: false
        default: 'true'
    platforms:
        required: false
        default: linux/amd64
    provenance:
        required: false
        default: 'false'
    secrets:
        required: false
        default: ""
    secret-envs:
        required: false
        default: ""
    secret-files:
        required: false
        default: ""

runs:
    using: composite
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ inputs.aws-access-key-id }}
            aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
            aws-region: ${{ inputs.aws-region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Make Docker Image Name
        env:
            registry: ${{ steps.login-ecr.outputs.registry }}
            repository: ${{ inputs.repository }}
            image_tag: ${{ inputs.image-tag }}
        run: echo "DOCKER_IMAGE_NAME_WITH_TAG=$registry/$repository:$image_tag" >> $GITHUB_ENV
        shell: bash

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
            version: latest

      - name: Docker Build and Push
        uses: docker/build-push-action@v6
        with:
            build-args: ${{ inputs.build-args }}
            build-contexts: ${{ inputs.build-contexts }}
            cache-from: ${{ inputs.cache-from }}
            cache-to: ${{ input.cache-to }}
            context: ${{ inputs.context }}
            file: ${{ inputs.build-file }}
            push: ${{ inputs.push }}
            platforms: ${{ inputs.platforms }}
            secrets: ${{ inputs.secrets }}
            secret-envs: ${{ inputs.secret-envs }}
            secret-files: ${{ inputs.secret-files }}
            tags: ${{ env.DOCKER_IMAGE_NAME_WITH_TAG }}
            provenance: ${{ inputs.provenance }}
