name: Docker Build ECR and Push
description: Docker build and ECR push
inputs:
    aws-access-key-id:
        required: true
    aws-secret-access-key:
        required: true
    aws-region:
        required: false
        default: ap-northeast-2
    repository:
        required: true
    image-tag:
        required: false
        default: latest
    build-platforms:
        required: false
        default: linux/amd64
    build-context:
        required: false
        default: .
    build-file:
        required: false
        default: ./Dockerfile
    build-args:
        required: false
        default: ""

runs:
    using: composite
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ inputs.aws-access-key-id }}
            aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
            aws-region: ${{ inputs.aws-region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Make Docker Image Name
        env:
            registry: ${{ steps.login-ecr.outputs.registry }}
            repository: ${{ inputs.repository }}
            image_tag: ${{ inputs.image-tag }}
        run: echo "DOCKER_IMAGE_NAME_WITH_TAG=$registry/$repository:$image_tag" >> $GITHUB_ENV
        shell: bash

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
            version: latest

      - name: Docker Build and Push
        uses: docker/build-push-action@v6
        with:
            push: true
            cache-from: type=gha
            cache-to: type=gha,mode=max
            build-context: ${{ inputs.build-context }}
            file: ${{ inputs.build-file }}
            tags: ${{ env.DOCKER_IMAGE_NAME_WITH_TAG }}
            provenance: false
            build-args: ${{ inputs.build-args }}
